# Generated by Django 5.2.5 on 2025-08-29 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('password_hash', models.CharField(max_length=128)),
                ('social_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'App User',
                'verbose_name_plural': 'App Users',
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Admin User', 'verbose_name_plural': 'Admin Users'},
        ),
    ]
